# Generated by Django 5.1.7 on 2025-03-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='ProfileDefaultAvatar.jpg', upload_to='profile_pics/'),
        ),
    ]
