# Generated by Django 5.1.7 on 2025-03-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_updated_at_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
