# Generated by Django 5.1.7 on 2025-05-07 20:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_image_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://asset.cloudinary.com/dwsmidse8/d0565a1f6cc802368986de1c1f036afc', max_length=255, null=True, verbose_name='image'),
        ),
    ]
