# Generated by Django 5.1.7 on 2025-05-07 21:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dwsmidse8/image/upload/v1746387500/defaultAvatar_lnamq0.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
