# Generated by Django 5.1.4 on 2024-12-27 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelspace', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reels',
            new_name='Reel',
        ),
        migrations.AlterModelOptions(
            name='reel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='signed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(choices=[('text', 'text'), ('image', 'image'), ('video', 'video')], default='video', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reelspace.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Feeds',
        ),
    ]
