# Generated by Django 5.1.5 on 2025-01-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
