# Generated by Django 5.1.4 on 2024-12-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelspace', '0002_rename_reels_reel_alter_reel_options_user_signed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=25),
        ),
    ]
