# Generated by Django 5.1.5 on 2025-01-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelspace', '0002_alter_user_date_joined_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
