# Generated by Django 5.1.4 on 2024-12-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelspace', '0003_alter_user_firstname_alter_user_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
