# Generated by Django 5.1.4 on 2024-12-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelspace', '0004_remove_user_age_user_email_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferredNickname',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
