# Generated by Django 5.1.4 on 2024-12-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reelspace', '0006_rename_user_customuser_alter_feed_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='preferredNickname',
        ),
    ]
