# Generated by Django 5.1.4 on 2025-01-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelspace', '0007_remove_customuser_preferrednickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
