# Generated by Django 5.1.4 on 2025-01-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reelspace', '0008_remove_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='user',
        ),
    ]
