# Generated by Django 5.1.4 on 2025-01-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reelspace', '0009_delete_customuser_remove_feed_user_remove_reel_user'),
    ]


    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.DeleteModel(
            name='Reel',
        ),
    ]
