# Generated by Django 5.1.4 on 2025-01-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelspace', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
